config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'cars#index'

  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  # Associations
  belongs_to :user
  # Validations
  validates_presence_of :make, :model, :color, :year, :mileage
  # Callbacks
  # Instance Methods
  # Example: car.find(1).info
  def info
    "The Car With Make: #{make} - #{model} has the color of #{color}"
  end

  # Class Methods
  # Example: @cars = Car.all.by_year
  def self.by_year
  # order(year: :desc)
  order(:year)
  end
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Associations
  has_many :cars, dependent: :destroy
  # Validatons
  # Callbacks
  # Instance Methods
  # Class Methods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Making sure a user is logged in - DOCS
  before_action :authenticate_user!
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, except: [:index, :new, :create]

  def index
    @cars = current_user.cars
  end

  def show
  end

  def new
    @car = current_user.cars.new
  end

  def create
    @car = current_user.cars.new(car_params)
    if @car.save
      redirect_to @car, notice: 'Car Created!'
    else
      render :new
    end
  end

  def edit
  end


  def update
    # our before action is doing this for us
    # @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end
  end

  def destroy
    # our before action is doing this for us
    # @car = Car.find(params[:id])
    @car.destroy
    flash[:notice] = 'Car Deleted!'
    redirect_to cars_path
  end

  # Before Actions
  private
    # Strong Params
  def car_params
    params.require(:car).permit(:make, :model,
                                :color, :year,
                                :mileage, :runs)
  end

    # Before Action
  def set_car
    @car = current_user.cars.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<% if @car.errors.any? %>
  <h4> <%= @car.errors.count %> Errors Saving The Car </h4>
  <% @car.errors.full_messages.each do |message| %>
    <h6 class='danger-text'> <%= message %> </h6>
  <% end %>
<% end %>

<%= form_for @car, html: { class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :make, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :make, require: true, class: 'form-control', placeholder: 'Car Make' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :model, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :model, require: true, class: 'form-control', placeholder: 'Car Model' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :color, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :color, require: true, class: 'form-control', placeholder: 'Car Color' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :year, require: true, class: 'form-control', placeholder: 'Car Year' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mileage, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :mileage, require: true, class: 'form-control', placeholder: 'Car Mileage' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :runs, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.check_box :runs, require: true, class: 'form-control', checked: true %>
    </div>
  </div>
  <div class='text-center'>
    <%= f.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1> Editing: <%= @car.info %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/cars/index.html.erb
<h1> Cars For: <%= current_user.email %> </h1>
<hr />

<% if @cars.any? %>

  <ul class='list-group'>
    <% @cars.each do |car| %>
      <li class='list-group-item'>
        <%= car.info %>
        <%= link_to 'Show', car_path(car), class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_car_path(car), class: 'btn btn-warning' %>
        <%= link_to 'Delete', car_path(car),
                    class: 'btn btn-danger',
                    data: { confirm: 'Really Delete?' },
                    method: :delete %>
      </li>
    <% end %>
  </ul>

<% else %>
  <h3>No Cars, Go Buy One!</h3>
<% end %>

<%= link_to 'Buy New Car', new_car_path, class: 'btn btn-primary' %>

app/views/cars/new.html.erb
<h1> New Car For: <%= current_user.email %> </h1>
<hr />

<%= render(partial: 'form') %>

app/views/cars/show.html.erb
<h1>Cars#show</h1>
<p>Find me in app/views/cars/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Cars</title>
    <%= csrf_meta_tags %>

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <%= render(partial: 'shared/navbar') %>
  <%= render(partial: 'shared/flash') %>    
  <div class='container'>
    <%= yield %>
        </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, message| %>
    <div class='flash <%= type %>'>
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'My Cars', cars_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>